version: '4'
services:
  product-db:
    image: mongo:7.0.4
    container_name: shopping-product-mongodb
    volumes:
      - ./data/product-service:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=product
    ports:
      - "27021:27017"

  order-db:
    container_name: shopping-order-postgres
    image: postgres:15.5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: order
      PGDATA: /data/postgres
    volumes:
      - ./data/order-service:/data/postgres
      - ./docker/postgres/order-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  inventory-db:
    container_name: shopping-inventory-postgres
    image: postgres:15.5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: inventory
      PGDATA: /data/postgres
    volumes:
      - ./data/inventory-service:/data/postgres
      - ./docker/postgres/inventory-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    restart: unless-stopped

  keycloak-db:
    container_name: shopping-keycloak-postgres
    image: postgres:15.5
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5430:5432"
    volumes:
      - ./data/keycloak:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: shopping-keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-db
